# Generated by Django 3.1.5 on 2021-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='logapp/images')),
                ('text', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
