# Generated by Django 3.1.5 on 2021-01-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmsg',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='postmsg',
            name='text',
            field=models.CharField(default='', max_length=30000),
        ),
    ]
