# Generated by Django 3.1.5 on 2021-01-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0003_auto_20210112_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmsg',
            name='text',
            field=models.CharField(max_length=30000),
        ),
    ]
