# Generated by Django 3.1.5 on 2021-01-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0005_auto_20210114_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmsg',
            name='coverphoto',
            field=models.ImageField(default='', upload_to='logapp/images'),
        ),
        migrations.AddField(
            model_name='postmsg',
            name='profile',
            field=models.ImageField(default='', upload_to='logapp/images'),
        ),
    ]
