# Generated by Django 3.1.5 on 2021-01-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0006_auto_20210122_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilecover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='', upload_to='logapp/images')),
                ('coverphoto', models.ImageField(default='', upload_to='logapp/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='postmsg',
            name='coverphoto',
        ),
        migrations.RemoveField(
            model_name='postmsg',
            name='profile',
        ),
    ]
