# Generated by Django 3.1.5 on 2021-01-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0007_auto_20210125_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecover',
            name='nme',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
