# Generated by Django 3.1.5 on 2021-03-30 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logapp', '0010_likescount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likescount',
            unique_together={('usernm', 'postnm', 'check')},
        ),
    ]
