# Generated by Django 3.1.5 on 2021-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0011_auto_20210330_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmsg',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmsg',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
